import Head from 'next/head';
import {type FC} from 'react';
import Loading from '@/components/Loading';
import Toast from '@/components/ToastCustom';

interface Props {
  title?: string;
  isLoading: boolean;
}

const Pre: FC<Props> = ({title, isLoading}) => (
  <>
    <Toast />
    {isLoading && <Loading />}
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  </>
);

export default Pre;
