import Head from 'next/head';
import React, { type FC, type ReactElement } from 'react';

interface Props {
  title?: string
}

const Pre: FC<Props> = ({ title }): ReactElement => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Pre;
